### PR TITLE
Code Cleanup

### PR DESCRIPTION
**Pull request by GamingGeek**
I just cleaned up some code (removed parenthesis from if statements, changed == None to is None etc.) and changed a while loop to use the tasks extension from discord.py

There's a ton more I could do but this is just some basic cleanup because this is full of spaghetti code 😂

Warning: I was unable to get the bot actually running but I was able to get it to start with no SyntaxError's so there may be some issues with my cleanup but hopefully not  :)

### CODE REVIEW

**Review by fbjac01 — APPROVED** [review]

**Comment by D1STR4CT** [comment]
I do approve of the effort to adhere to coding standard but I don’t think you should change the way functions are named because of this. 

I’m leaving this up to the other people who work more on this code to decide

**Review by showengineer — CHANGES_REQUESTED** [review]
Hi. Thanks for your pull request! I'd admit some low-level stuff is spaghetti code (especially the error handling lol). Just wanna let you know that although this bot is already deployed the bot is still in beta. 

There are a few things I want to point out. 
1. The naming scheme in `db.py` is intentional. low-level stuff like `_sql_check_muted()` are in under_score while the functions that are actually called are in CamelCase. I applaud the edits where I didn't do that, my bad :) (like in elevatedperms.py)
2. Personally not a big fan of newlines in functions, but that's because everything fits on my widescreen
3. If-statements are C-style since the initial devs are coming from C/C++/C#. I don't mind changing this style since it does make it more readable to the average python coder. Again, IMO this is a personal preference and since we don't have a coding standard _yet_ this is up for debate.

**Comment by showengineer** [comment]
Tested your branch and it runs without problems.

**Comment by GamingGeek** [comment]
I appreciate the comment. I've gone ahead and made some changes according to your points

> The naming scheme in db.py is intentional. low-level stuff like _sql_check_muted() are in under_score while the functions that are actually called are in CamelCase. I applaud the edits where I didn't do that, my bad :) (like in elevatedperms.py)

I have reverted it to the CamelCase naming in db.py and fixed references

> Personally not a big fan of newlines in functions, but that's because everything fits on my widescreen

Also went ahead and reverted this. I'm not the biggest fan of them either but PyCharm does it automatically so I usually just leave it be.

> If-statements are C-style since the initial devs are coming from C/C++/C#. I don't mind changing this style since it does make it more readable to the average python coder. Again, IMO this is a personal preference and since we don't have a coding standard yet this is up for debate.

I left my changes in this regard alone as I do feel it's easier to read, especially when using functions in if statements

**Review by showengineer — APPROVED** [review]
Hi! Thanks for the changes and especially the cleanup. Since almost all the features are there I can try rewriting it to make it less spaghetti. It is currently built to make it as efficient as possible on one thread.

Again tested, no problems found

**Comment by Aryyel** [comment]
Approved

**Pull request merged**
